### ISSUE TITLE
Windows: basic test failed

### ISSUE THREAD

**Issue by yceny** [google-research/batch_rl#39]
I am on Windows, and run the basic test `python -um batch_rl.tests.atari_init_test`. But it failed. 

Here is the traceback:

Running tests under Python 3.9.12: C:\Users\cenyyang\Anaconda3\python.exe
[ RUN      ] AtariInitTest.test_atari_init
INFO:tensorflow:Saving replay buffer data to C:\Users\cenyyang\OneDrive\ -\ City\ University\ of\ Hong Kong\batch_rl\replay_logs
I0131 22:32:19.065589 27504 train.py:75] Saving replay buffer data to C:\Users\cenyyang\OneDrive\ -\ City\ University\ of\ Hong Kong\batch_rl\replay_logs
W0131 22:32:19.066590 27504 run_experiment.py:267] DEPRECATION WARNING: Logger is being deprecated. Please switch to CollectorDispatcher!
INFO:tensorflow:time(__main__.AtariInitTest.test_atari_init): 0.02s
I0131 22:32:19.066590 27504 test_util.py:2462] time(__main__.AtariInitTest.test_atari_init): 0.02s
[  FAILED  ] AtariInitTest.test_atari_init
[ RUN      ] AtariInitTest.test_session
[  SKIPPED ] AtariInitTest.test_session

ERROR: test_atari_init (__main__.AtariInitTest)
AtariInitTest.test_atari_init
Tests that a DQN agent is initialized.

Traceback (most recent call last):
  File "C:\Users\cenyyang\OneDrive - City University of Hong Kong\batch_rl\batch_rl\tests\atari_init_test.py", line 49, in test_atari_init
    train.main([])
  File "C:\Users\cenyyang\OneDrive - City University of Hong Kong\batch_rl\batch_rl\baselines\train.py", line 78, in main
    runner = LoggedRunner(FLAGS.base_dir, create_agent_fn)
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gin\config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gin\utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gin\config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gin\config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gin\utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gin\config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\dopamine\discrete_domains\run_experiment.py", line 222, in __init__
    self._environment = create_environment_fn()
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gin\config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gin\utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gin\config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\dopamine\discrete_domains\atari_lib.py", line 96, in create_atari_environment
    env = gym.make(full_game_name)
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gym\envs\registration.py", line 607, in make
    _check_version_exists(ns, name, version)
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gym\envs\registration.py", line 234, in _check_version_exists
    _check_name_exists(ns, name)
  File "C:\Users\cenyyang\Anaconda3\lib\site-packages\gym\envs\registration.py", line 212, in _check_name_exists
    raise error.NameNotFound(
gym.error.NameNotFound: Environment PongNoFrameskip doesn't exist.
  In call to configurable 'create_atari_environment' (<function create_atari_environment at 0x000001E26C2BB280>)
  In call to configurable 'Runner' (<class 'dopamine.discrete_domains.run_experiment.Runner'>)
  In call to configurable 'LoggedRunner' (<class 'batch_rl.baselines.run_experiment.LoggedRunner'>)

Ran 2 tests in 0.027s

FAILED (errors=1, skipped=1)

The error seems to be related to the base_dir?

**Comment by agarwl** [comment]
Hi @yceny, you can look at the more up-to-date working code in [dopamine/labs/offline_rl](https://github.com/google/dopamine/tree/master/dopamine/labs/offline_rl). Also, since this is offline RL, you'd only need the offline dataset and can use your favorite framework.
